spring.application.name=CitMobi

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/dbmobi
spring.datasource.username=postgres
spring.datasource.password=1234


# Hibernate settings (optional)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Flyway settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/mocks
spring.flyway.clean-disabled=true


# Application settings
logging.level.org.springframework=false
server.port=8080

