spring.application.name=ibgeConsumer

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/dbmobi
spring.datasource.username=citAdm
spring.datasource.password=1234


# Hibernate settings (optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Flyway settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration  # This is where Flyway looks for migrations
flyway.cleanDisabled=false


# Application settings
logging.level.org.springframework=false
server.port=8081
