spring.application.name=CitMobi

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/dbmobi
spring.datasource.username=postgres
spring.datasource.password=1234


# Flyway settings
flyway.enabled=true
flyway.url=jdbc:postgresql://localhost:5432/dbmobi
flyway.user=postgres
flyway.password=1234
flyway.locations=classpath:migrations  # This is where Flyway looks for migrations
flyway.cleanDisabled=true

# Application settings
logging.level.org.springframework=false
server.port=8085
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

