--CREATE SCHEMA Mobi;

CREATE TABLE T_GLB_UF (
    GLB_UF_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_UF_NOME VARCHAR(100),
    GLB_UF_SIGLA VARCHAR(2) UNIQUE
);

CREATE TABLE T_GLB_MUNICIPIO (
    GLB_MUNICIPIO_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_MUNICIPIO_NOME VARCHAR(150),
    GLB_UF_SIGLA VARCHAR(4),
    CONSTRAINT FK_GLB_UF_SIGLA FOREIGN KEY(GLB_UF_SIGLA)
        REFERENCES T_GLB_UF(GLB_UF_SIGLA)
);

CREATE TABLE T_GLB_OPERADOR (
    GLB_OPERADOR_CNPJ VARCHAR(14) NOT NULL,
    GLB_OPERADOR_RAZAOSOCIAL VARCHAR(255) NOT NULL,
    GLB_OPERADOR_FLAGREGULADOR VARCHAR(1) DEFAULT 'S' NOT NULL CHECK (GLB_OPERADOR_FLAGREGULADOR IN ('S', 'N')),
    PRIMARY KEY (GLB_OPERADOR_CNPJ)
);

CREATE TABLE T_LIN_TIPO (
    LIN_TIPO_ID INT NOT NULL PRIMARY KEY,
    LIN_TIPO_DESCRICAO VARCHAR(150) NOT NULL
);

CREATE TABLE T_LIN_TERMINAL (
    LIN_TERMINAL_NOME VARCHAR(255) NOT NULL UNIQUE,
    LIN_TERMINAL_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_NUMERO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_LATITUDE Decimal(8,6) NOT NULL,
    LIN_TERMINAL_LONGITUDE Decimal(9,6) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(2) NOT NULL,
    LIN_TIPO_ID INT NOT NULL,
    PRIMARY KEY (LIN_TERMINAL_NOME, GLB_MUNICIPIO_COD),
    FOREIGN KEY (GLB_UF_SIGLA) REFERENCES T_GLB_UF(GLB_UF_SIGLA),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);

-- Create the T_LIN_PARADA table
CREATE TABLE T_LIN_PARADA (
    --LIN_PARADA_ID BIGINT NOT NULL AUTO_INCREMENT, SQL
    LIN_PARADA_ID BIGSERIAL NOT NULL,
    LIN_PARADA_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_PARADA_NUMERO VARCHAR(255) NULL,
    LIN_PARADA_OBS VARCHAR(255) NULL,
    LIN_PARADA_LATITUDE Decimal(8,6) NOT NULL,
    LIN_PARADA_LONGITUDE Decimal(9,6) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(4) NOT NULL,
    LIN_TIPO_ID INT NOT NULL,
    LIN_PARADA_FLAGATIVA VARCHAR(1) NOT NULL,
    PRIMARY KEY (LIN_PARADA_ID),
    FOREIGN KEY (GLB_UF_SIGLA) REFERENCES T_GLB_UF(GLB_UF_SIGLA),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);

CREATE TABLE T_LIN_LINHA (
    LIN_LINHA_ID VARCHAR(30) NOT NULL, -- linhaId
    LIN_LINHA_ATENDIMENTO VARCHAR(15) NOT NULL, -- linhaId
    LIN_LINHA_DESCRICAO VARCHAR(255) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL, -- linhaId
    LIN_LINHA_FLAGINTERMUNICIPAL VARCHAR(1) NOT NULL CHECK (LIN_LINHA_FLAGINTERMUNICIPAL IN ('S', 'N')),
    LIN_LINHA_FLAGATENDEMETRO VARCHAR(1) NOT NULL CHECK (LIN_LINHA_FLAGATENDEMETRO IN ('S', 'N')),
    LIN_LINHA_FLAGATENDETREM VARCHAR(1) NOT NULL CHECK (LIN_LINHA_FLAGATENDETREM IN ('S', 'N')),
    LIN_LINHA_FLAGATIVA VARCHAR(1) DEFAULT 'S' NOT NULL CHECK (LIN_LINHA_FLAGATIVA IN ('S', 'N')),
    PRIMARY KEY (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO (GLB_MUNICIPIO_COD)
);

CREATE TABLE T_LIN_LINHA_OPERADOR(
    GLB_OPERADOR_CNPJ VARCHAR(14) NOT NULL,
    LIN_LINHA_ID VARCHAR(30) NOT NULL, -- linhaId
    LIN_LINHA_ATENDIMENTO VARCHAR(15) NOT NULL, -- linhaId
    GLB_MUNICIPIO_COD BIGINT NOT NULL, -- linhaId
    PRIMARY KEY (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD, GLB_OPERADOR_CNPJ),
    FOREIGN KEY (GLB_OPERADOR_CNPJ) REFERENCES T_GLB_OPERADOR (GLB_OPERADOR_CNPJ),
    FOREIGN KEY (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD) REFERENCES T_LIN_LINHA(LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
);

CREATE TABLE T_LIN_ROTA (
   LIN_ROTA_ID bigserial NOT NULL,
   LIN_LINHA_ID varchar(30) NOT NULL,
   LIN_LINHA_ATENDIMENTO varchar(15) NOT NULL,
   LIN_ROTA_PREFIXO varchar(255) NOT NULL,
   GLB_MUNICIPIO_COD BIGINT NOT NULL,
   LIN_ROTA_SENTIDO varchar(12) NOT NULL,
   PRIMARY KEY(LIN_ROTA_ID),
   FOREIGN KEY(GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
   FOREIGN KEY (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD) REFERENCES T_LIN_LINHA(LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
);

CREATE TABLE T_LIN_ITINERARIO (
  LIN_ROTA_ID BIGINT NOT NULL,
  LIN_PARADA_ID BIGINT NOT NULL,
  LIN_ITINERARIO_SEQUENCIA INT NOT NULL,

  PRIMARY KEY(LIN_ROTA_ID, LIN_PARADA_ID, LIN_ITINERARIO_SEQUENCIA),
  FOREIGN KEY(LIN_PARADA_ID) REFERENCES T_LIN_PARADA(LIN_PARADA_ID),
  FOREIGN KEY(LIN_ROTA_ID) REFERENCES T_LIN_ROTA(LIN_ROTA_ID)
);
