--CREATE SCHEMA Mobi;

CREATE TABLE T_GLB_UF (
    GLB_UF_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_UF_NOME VARCHAR(100),
    GLB_UF_SIGLA VARCHAR(2) UNIQUE
);

CREATE TABLE T_GLB_MUNICIPIO (
    GLB_MUNICIPIO_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_MUNICIPIO_NOME VARCHAR(150),
    GLB_UF_SIGLA VARCHAR(4),
    CONSTRAINT FK_GLB_UF_SIGLA FOREIGN KEY(GLB_UF_SIGLA)
        REFERENCES T_GLB_UF(GLB_UF_SIGLA)
);

CREATE TABLE T_LIN_TIPO (
    LIN_TIPO_ID INT NOT NULL PRIMARY KEY,
    LIN_TIPO_DESCRICAO VARCHAR(150) NOT NULL
);

CREATE TABLE T_LIN_TERMINAL (
    LIN_TERMINAL_NOME VARCHAR(255) NOT NULL UNIQUE,
    LIN_TERMINAL_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_NUMERO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_LATITUDE Decimal(8,6) NOT NULL,
    LIN_TERMINAL_LONGITUDE Decimal(9,6) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(2) NOT NULL,
    LIN_TIPO_ID INT NOT NULL,
    PRIMARY KEY (LIN_TERMINAL_NOME, GLB_MUNICIPIO_COD),
    FOREIGN KEY (GLB_UF_SIGLA) REFERENCES T_GLB_UF(GLB_UF_SIGLA),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);

-- Create the T_LIN_PARADA table
CREATE TABLE T_LIN_PARADA (
    --LIN_PARADA_ID BIGINT NOT NULL AUTO_INCREMENT, SQL
    LIN_PARADA_ID BIGSERIAL NOT NULL,
    LIN_PARADA_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_PARADA_NUMERO VARCHAR(255) NOT NULL,
    LIN_PARADA_LATITUDE Decimal(8,6) NOT NULL,
    LIN_PARADA_LONGITUDE Decimal(9,6) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(4) NOT NULL,
    LIN_TIPO_ID INT NOT NULL,
    PRIMARY KEY (LIN_PARADA_ID, GLB_MUNICIPIO_COD),
    FOREIGN KEY (GLB_UF_SIGLA) REFERENCES T_GLB_UF(GLB_UF_SIGLA),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);

CREATE TABLE T_LIN_LINHA (

    LIN_LINHA_ID VARCHAR(30) NOT NULL, -- linhaId
    LIN_LINHA_ATENDIMENTO VARCHAR(15) NOT NULL, -- linhaId
    LIN_LINHA_DESCRICAO VARCHAR(255) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL, -- linhaId
    GLB_OPERADOR_CNPJOPERADOR VARCHAR(18) NOT NULL,
    LIN_LINHA_FLAGINTERMUNICIPAL VARCHAR(1) NOT NULL,
    LIN_LINHA_FLAGATENDEMETRO VARCHAR(1) NOT NULL,
    LIN_LINHA_FLAGATENDETREM VARCHAR(1) NOT NULL,
    PRIMARY KEY(LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD)
);

CREATE TABLE T_LIN_ITINERARIO (
   LIN_LINHA_ID varchar(30) NOT NULL,
   LIN_LINHA_ATENDIMENTO varchar(15) NOT NULL,
   LIN_LINHA_PREFIXO varchar(255) NOT NULL,
   LIN_PARADA_ID bigserial NOT NULL,
   GLB_MUNICIPIO_COD bigint NOT NULL,
   LIN_ITINERARIO_SENTIDO varchar(12) NOT NULL,
   LIN_ITINERARIO_SEQUENCIA INT NOT NULL,
   PRIMARY KEY(LIN_PARADA_ID,LIN_ITINERARIO_SEQUENCIA,LIN_LINHA_ID,LIN_LINHA_ATENDIMENTO,GLB_MUNICIPIO_COD,LIN_ITINERARIO_SENTIDO),
   FOREIGN KEY(GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
   FOREIGN KEY (LIN_PARADA_ID, GLB_MUNICIPIO_COD) REFERENCES T_LIN_PARADA(LIN_PARADA_ID, GLB_MUNICIPIO_COD),
   FOREIGN KEY (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
   REFERENCES T_LIN_LINHA(LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
);


