CREATE SCHEMA IF NOT EXISTS ibge;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS ibge.T_GLB_UF (
    GLB_UF_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_UF_NOME VARCHAR(100),
    GLB_UF_SIGLA VARCHAR(2) UNIQUE
);

CREATE TABLE IF NOT EXISTS ibge.T_GLB_MUNICIPIO (
    GLB_MUNICIPIO_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_MUNICIPIO_NOME VARCHAR(150),
    GLB_UF_SIGLA VARCHAR(2),
    CONSTRAINT FK_GLB_UF_SIGLA FOREIGN KEY(GLB_UF_SIGLA)
        REFERENCES ibge.T_GLB_UF(GLB_UF_SIGLA)
);

CREATE TABLE T_GLB_OPERADOR (
    GLB_OPERADOR_ID BIGSERIAL PRIMARY KEY,
    GLB_OPERADOR_CNPJ VARCHAR(14) UNIQUE NOT NULL,
    GLB_OPERADOR_RAZAOSOCIAL VARCHAR(255) NOT NULL,
    GLB_OPERADOR_FLAGREGULADOR VARCHAR(1) DEFAULT 'S' NOT NULL CHECK (GLB_OPERADOR_FLAGREGULADOR IN ('S', 'N'))
);

CREATE TABLE T_LIN_TIPO (
    LIN_TIPO_ID INT NOT NULL PRIMARY KEY,
    LIN_TIPO_DESCRICAO VARCHAR(150) NOT NULL
);

CREATE TABLE T_LIN_TERMINAL (
    LIN_TERMINAL_ID BIGSERIAL PRIMARY KEY,
    LIN_TERMINAL_NOME VARCHAR(255) NOT NULL,
    LIN_TERMINAL_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_NUMERO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_LATITUDE DECIMAL(8,6) NOT NULL,
    LIN_TERMINAL_LONGITUDE DECIMAL(9,6) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(2) NOT NULL,
    LIN_TIPO_ID INT NOT NULL,
    CONSTRAINT UK_TERMINAL_NOME_MUNICIPIO UNIQUE (LIN_TERMINAL_NOME, GLB_MUNICIPIO_COD),
    CONSTRAINT FK_TERMINAL_UF FOREIGN KEY (GLB_UF_SIGLA) REFERENCES ibge.T_GLB_UF(GLB_UF_SIGLA),
    CONSTRAINT FK_TERMINAL_MUNICIPIO FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES ibge.T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    CONSTRAINT FK_TERMINAL_TIPO FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);

CREATE TABLE T_LIN_PARADA (
    LIN_PARADA_ID BIGSERIAL PRIMARY KEY,
    LIN_PARADA_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_PARADA_NUMERO VARCHAR(255) NULL,
    LIN_PARADA_OBS VARCHAR(255) NULL,
    LIN_PARADA_LATITUDE DECIMAL(8,6) NOT NULL,
    LIN_PARADA_LONGITUDE DECIMAL(9,6) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(2) NOT NULL,
    LIN_TIPO_ID INT NOT NULL,
    LIN_PARADA_FLAGATIVA VARCHAR(1) DEFAULT 'S' NOT NULL CHECK (LIN_PARADA_FLAGATIVA IN ('S', 'N')),
    CONSTRAINT FK_PARADA_UF FOREIGN KEY (GLB_UF_SIGLA) REFERENCES ibge.T_GLB_UF(GLB_UF_SIGLA),
    CONSTRAINT FK_PARADA_MUNICIPIO FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES ibge.T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    CONSTRAINT FK_PARADA_TIPO FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);

CREATE TABLE T_LIN_LINHA (
    LIN_LINHA_ID BIGSERIAL PRIMARY KEY,
    LIN_LINHA_CODIGO VARCHAR(30) NOT NULL,
    LIN_LINHA_ATENDIMENTO VARCHAR(15) NOT NULL,
    LIN_LINHA_DESCRICAO VARCHAR(255) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_OPERADOR_ID BIGINT NOT NULL,
    LIN_LINHA_FLAGINTERMUNICIPAL VARCHAR(1) DEFAULT 'N' NOT NULL CHECK (LIN_LINHA_FLAGINTERMUNICIPAL IN ('S', 'N')),
    LIN_LINHA_FLAGATENDEMETRO VARCHAR(1) DEFAULT 'N' NOT NULL CHECK (LIN_LINHA_FLAGATENDEMETRO IN ('S', 'N')),
    LIN_LINHA_FLAGATENDETREM VARCHAR(1) DEFAULT 'N' NOT NULL CHECK (LIN_LINHA_FLAGATENDETREM IN ('S', 'N')),
    LIN_LINHA_FLAGATIVA VARCHAR(1) DEFAULT 'S' NOT NULL CHECK (LIN_LINHA_FLAGATIVA IN ('S', 'N')),
    CONSTRAINT UK_LINHA_COD_ATEND_MUN UNIQUE (LIN_LINHA_CODIGO, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD),
    CONSTRAINT FK_LINHA_MUNICIPIO FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES ibge.T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    CONSTRAINT FK_LINHA_OPERADOR FOREIGN KEY (GLB_OPERADOR_ID) REFERENCES T_GLB_OPERADOR(GLB_OPERADOR_ID)
);

CREATE TABLE T_LIN_ROTA (
    LIN_ROTA_ID BIGSERIAL PRIMARY KEY,
    LIN_LINHA_ID BIGINT NOT NULL,
    LIN_ROTA_PREFIXO VARCHAR(255) NOT NULL,
    LIN_ROTA_SENTIDO VARCHAR(12) NOT NULL,
    CONSTRAINT FK_ROTA_LINHA FOREIGN KEY (LIN_LINHA_ID) REFERENCES T_LIN_LINHA(LIN_LINHA_ID)
);

CREATE TABLE T_LIN_ITINERARIO (
    LIN_ITINERARIO_ID BIGSERIAL PRIMARY KEY,
    LIN_ROTA_ID BIGINT NOT NULL,
    LIN_PARADA_ID BIGINT NOT NULL,
    LIN_ITINERARIO_SEQUENCIA INT NOT NULL,
    CONSTRAINT UK_ITINERARIO_ROTA_SEQ UNIQUE (LIN_ROTA_ID, LIN_ITINERARIO_SEQUENCIA),
    CONSTRAINT FK_ITINERARIO_ROTA FOREIGN KEY (LIN_ROTA_ID) REFERENCES T_LIN_ROTA(LIN_ROTA_ID),
    CONSTRAINT FK_ITINERARIO_PARADA FOREIGN KEY (LIN_PARADA_ID) REFERENCES T_LIN_PARADA(LIN_PARADA_ID)
);

