-- Clean up existing user tables if any
DROP TABLE IF EXISTS T_USU_USUARIO_ACESSO CASCADE;
DROP TABLE IF EXISTS T_USU_USUARIO CASCADE;

CREATE TABLE T_USU_USUARIO (
    USU_USUARIO_ID              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USU_USUARIO_LOGIN           VARCHAR(50) UNIQUE NOT NULL,
    GLB_OPERADOR_ID             BIGINT NOT NULL,
    USU_USUARIO_EMAIL           VARCHAR(255) UNIQUE NOT NULL
                                CHECK (USU_USUARIO_EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    USU_USUARIO_SENHA           TEXT NOT NULL,
    USU_USUARIO_NOME            VARCHAR(100),
    USU_USUARIO_TELEFONE        VARCHAR(20) UNIQUE CHECK (USU_USUARIO_TELEFONE ~ '^[0-9]+$'),
    USU_USUARIO_CPF             VARCHAR(11) UNIQUE,
    USU_USUARIO_ROLE            VARCHAR(25) NOT NULL CHECK (USU_USUARIO_ROLE IN ('ADMIN', 'USER', 'MODERATOR', 'MOTORISTA')),
    USU_USUARIO_FLAGATIVO       TEXT NOT NULL DEFAULT 'S' CHECK (USU_USUARIO_FLAGATIVO IN ('S', 'N')),
    USU_USUARIO_DTCRIACAO       TIMESTAMPTZ DEFAULT now(),
    USU_USUARIO_DTUPDATE        TIMESTAMPTZ NULL,
    USU_USUARIO_DTULTIMOLOGIN   TIMESTAMPTZ,
    CONSTRAINT FK_USU_OPERADOR_ID FOREIGN KEY (GLB_OPERADOR_ID)
        REFERENCES T_GLB_OPERADOR (GLB_OPERADOR_ID)
);

CREATE TABLE T_USU_USUARIO_ACESSO (
    USU_ACESSO_ID               BIGSERIAL PRIMARY KEY,
    USU_USUARIO_ID              UUID NOT NULL,
    GLB_MUNICIPIO_COD           BIGINT NULL,
    GLB_UF_COD                  BIGINT NULL,
    CONSTRAINT FK_ACESSO_USUARIO FOREIGN KEY (USU_USUARIO_ID)
        REFERENCES T_USU_USUARIO (USU_USUARIO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACESSO_MUNICIPIO FOREIGN KEY (GLB_MUNICIPIO_COD)
        REFERENCES ibge.T_GLB_MUNICIPIO (GLB_MUNICIPIO_COD),
    CONSTRAINT FK_ACESSO_UF FOREIGN KEY (GLB_UF_COD)
        REFERENCES ibge.T_GLB_UF (GLB_UF_COD)
);

-- Create Indexes
CREATE INDEX idx_usuario_login ON T_USU_USUARIO(USU_USUARIO_LOGIN);
CREATE INDEX idx_usuario_email ON T_USU_USUARIO(USU_USUARIO_EMAIL);
CREATE INDEX idx_usuario_role ON T_USU_USUARIO(USU_USUARIO_ROLE);
CREATE INDEX idx_usuario_status ON T_USU_USUARIO(USU_USUARIO_FLAGATIVO);
CREATE INDEX idx_usu_operador_id ON T_USU_USUARIO(GLB_OPERADOR_ID);
CREATE INDEX idx_usuario_acesso_user ON T_USU_USUARIO_ACESSO(USU_USUARIO_ID);