INSERT INTO T_GLB_UF (GLB_UF_COD, GLB_UF_NOME, GLB_UF_SIGLA) VALUES (35, 'São Paulo', 'SP');
INSERT INTO T_GLB_MUNICIPIO (GLB_MUNICIPIO_COD, GLB_MUNICIPIO_NOME, GLB_UF_SIGLA)
VALUES (3550308, 'São Paulo', 'SP');

-- TO DO:

INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('31974104000120', 'VIACAO METROPOLE PAULISTA S/A', 'N');
INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('01751967000178', 'SAMBAIBA TRANSPORTES URBANOS LTDA.', 'N');
INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('60870847000159', 'VIACAO GATO PRETO LTDA', 'N');
INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('61274809000104', 'VIAÇÃO SANTA BRIGIDA LTDA', 'N');
INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('20589286000108', 'PESSEGO TRANSPORTES LTDA', 'N');
INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('60498417000158', 'SÃO PAULO TRANSPORTE S/A', 'S');
INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('41814509000155', 'AGENCIA REGULADORA DE SERVICOS PUBLICOS DO MUNICIPIO DE SAO PAULO SP REGULA', 'S');
INSERT INTO T_GLB_OPERADOR(GLB_OPERADOR_CNPJ, GLB_OPERADOR_RAZAOSOCIAL, GLB_OPERADOR_FLAGREGULADOR) VALUES ('46392155000111', 'SECRETARIA MUNICIPAL DE MOBILIDADE E TRANSITO - SMT', 'S');



INSERT INTO T_LIN_TIPO (LIN_TIPO_ID, LIN_TIPO_DESCRICAO) VALUES (1,'TERMINAL');  -- Terminal
INSERT INTO T_LIN_TIPO (LIN_TIPO_ID, LIN_TIPO_DESCRICAO) VALUES (2, 'PONTO');  -- Ponto


-- Seria bom pensar em um metodo de apelidos para certos pontos.
-- Mock data for Parada
INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('R. Carlos Aguiar', '14',  -23.502900369721317, -46.380309377909775, 3550308, 'SP', 2, 'S');

INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('R. Padre Virgílio Campelo', '20', -23.50423248279265, -46.379010930154536, 3550308, 'SP', 2, 'S');

-- METRO BRESSER
INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('R. Ipanema', '686',  -23.547132863498348, -46.607014567557705, 3550308, 'SP', 2, 'S');
INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('R. Bresser', '1954',  -23.546751763425107, -46.60406242955317, 3550308, 'SP', 2, 'S');
INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('Av. Alcantara Machado', '2576',  -23.54749971477409, -46.60097044345936, 3550308, 'SP', 2, 'S');
INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('R. Jaibaras', '299',  -23.548135181630453, -46.597157768018384, 3550308, 'SP', 2, 'S');
INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('R. Taquari', '556',  -23.551418626046, -46.59781131264221, 3550308, 'SP', 2, 'S');
INSERT INTO T_LIN_PARADA (LIN_PARADA_LOGRADOURO, LIN_PARADA_NUMERO, LIN_PARADA_LATITUDE, LIN_PARADA_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID, LIN_PARADA_FLAGATIVA)
VALUES ('R. Bresser', '2695',  -23.55204480542456, -46.59978938713616, 3550308, 'SP', 2, 'S');
-- You can add more stops here as needed

-- Mock data for Terminal
INSERT INTO T_LIN_TERMINAL (LIN_TERMINAL_NOME, LIN_TERMINAL_LOGRADOURO, LIN_TERMINAL_NUMERO, LIN_TERMINAL_LATITUDE, LIN_TERMINAL_LONGITUDE, GLB_MUNICIPIO_COD, GLB_UF_SIGLA, LIN_TIPO_ID)
VALUES ('Terminal Penha', 'Av. Cangaíba', '130', -23.518623410647624, -46.54680953372933, 3550308, 'SP', 1);

-- Mock Data for Linhas
INSERT INTO T_LIN_LINHA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD, LIN_LINHA_DESCRICAO, LIN_LINHA_FLAGINTERMUNICIPAL, LIN_LINHA_FLAGATENDEMETRO, LIN_LINHA_FLAGATENDETREM, LIN_LINHA_FLAGATIVA)
VALUES('3301', '10', 3550308, 'TERMINAL SÃO MIGUEL - TERMINAL PARQUE DOM PEDRO II', 'N', 'N', 'N', 'S');

INSERT INTO T_LIN_LINHA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD, LIN_LINHA_DESCRICAO, LIN_LINHA_FLAGINTERMUNICIPAL, LIN_LINHA_FLAGATENDEMETRO, LIN_LINHA_FLAGATENDETREM, LIN_LINHA_FLAGATIVA)
VALUES('1178', '10', 3550308, 'TERMINAL SÃO MIGUEL - PÇA. DO CORREIO', 'N', 'N', 'N', DEFAULT);

INSERT INTO T_LIN_LINHA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD, LIN_LINHA_DESCRICAO, LIN_LINHA_FLAGINTERMUNICIPAL, LIN_LINHA_FLAGATENDEMETRO, LIN_LINHA_FLAGATENDETREM, LIN_LINHA_FLAGATIVA)
VALUES('9051', '10', 3550308, 'TERM. PINHEIROS - LAPA', 'N', 'N', 'N', 'S');

INSERT INTO T_LIN_LINHA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD, LIN_LINHA_DESCRICAO, LIN_LINHA_FLAGINTERMUNICIPAL, LIN_LINHA_FLAGATENDEMETRO, LIN_LINHA_FLAGATENDETREM, LIN_LINHA_FLAGATIVA)
VALUES('8000', '10', 3550308, 'PÇA. RAMOS DE AZEVEDO - TERM. LAPA', 'N', 'N', 'N', 'S');

INSERT INTO T_LIN_LINHA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD, LIN_LINHA_DESCRICAO, LIN_LINHA_FLAGINTERMUNICIPAL, LIN_LINHA_FLAGATENDEMETRO, LIN_LINHA_FLAGATENDETREM, LIN_LINHA_FLAGATIVA)
VALUES('372F', '10', 3550308, 'UNIVERSIDADE SÃO JUDAS TADEU - METRÔ BRESSER' , 'N', 'S', 'N', 'S');

-- Mock data for Linha operador
-- TERM SAO MIGUEL
INSERT INTO T_LIN_LINHA_OPERADOR (GLB_OPERADOR_CNPJ, LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
VALUES('31974104000120', '3301', '10', 3550308);
-- PRACA DO CORREIO
INSERT INTO T_LIN_LINHA_OPERADOR (GLB_OPERADOR_CNPJ, LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
VALUES('31974104000120', '1178', '10', 3550308);
-- LAPA SAMBAIBA
INSERT INTO T_LIN_LINHA_OPERADOR (GLB_OPERADOR_CNPJ, LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
VALUES('01751967000178', '9051', '10', 3550308);
-- LAPA GATO PRETO
INSERT INTO T_LIN_LINHA_OPERADOR (GLB_OPERADOR_CNPJ, LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
VALUES('60870847000159', '9051', '10', 3550308);
-- PCA RAMOS DE AZEVEDO - LAPA
INSERT INTO T_LIN_LINHA_OPERADOR (GLB_OPERADOR_CNPJ, LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
VALUES('61274809000104', '8000', '10', 3550308);
-- UNIVERSIDADE SAO JUDAS TADEU
INSERT INTO T_LIN_LINHA_OPERADOR (GLB_OPERADOR_CNPJ, LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
VALUES('20589286000108', '372F', '10', 3550308);

-- Mock data for Rota
INSERT INTO T_LIN_ROTA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, LIN_ROTA_PREFIXO, GLB_MUNICIPIO_COD, LIN_ROTA_SENTIDO)
VALUES('9051', '10', 'PÇA. RAMOS DE AZEVEDO', 3550308, 'IDA');
INSERT INTO T_LIN_ROTA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, LIN_ROTA_PREFIXO, GLB_MUNICIPIO_COD, LIN_ROTA_SENTIDO)
VALUES('9051', '10', 'TERM. LAPA', 3550308, 'VOLTA');
-- 372F-10
INSERT INTO T_LIN_ROTA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, LIN_ROTA_PREFIXO, GLB_MUNICIPIO_COD, LIN_ROTA_SENTIDO)
VALUES('372F', '10', 'UNIVERSIDADE SAO JUDAS TADEU', 3550308, 'IDA');
INSERT INTO T_LIN_ROTA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, LIN_ROTA_PREFIXO, GLB_MUNICIPIO_COD, LIN_ROTA_SENTIDO)
VALUES('372F', '10', 'METRO BRESSER', 3550308, 'VOLTA');

-- Mock for 372F Itinerario
INSERT INTO T_LIN_ITINERARIO (LIN_ROTA_ID, LIN_PARADA_ID, LIN_ITINERARIO_SEQUENCIA)
VALUES(4, 8, 1);
INSERT INTO T_LIN_ITINERARIO(LIN_ROTA_ID, LIN_PARADA_ID, LIN_ITINERARIO_SEQUENCIA)
VALUES(4, 7, 2);
INSERT INTO T_LIN_ITINERARIO(LIN_ROTA_ID, LIN_PARADA_ID, LIN_ITINERARIO_SEQUENCIA)
VALUES(4, 6, 3);
INSERT INTO T_LIN_ITINERARIO(LIN_ROTA_ID, LIN_PARADA_ID, LIN_ITINERARIO_SEQUENCIA)
VALUES(4, 5, 4);
INSERT INTO T_LIN_ITINERARIO(LIN_ROTA_ID, LIN_PARADA_ID, LIN_ITINERARIO_SEQUENCIA)
VALUES(4, 4, 5);
INSERT INTO T_LIN_ITINERARIO(LIN_ROTA_ID, LIN_PARADA_ID, LIN_ITINERARIO_SEQUENCIA)
VALUES(4, 3, 6);
