CREATE TABLE T_LIN_TERMINAL (
    LIN_TERMINAL_NOME VARCHAR(255) NOT NULL UNIQUE,
    LIN_TERMINAL_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_NUMERO VARCHAR(255) NOT NULL,
    LIN_TERMINAL_LATITUDE Decimal(8,6) NOT NULL,
    LIN_TERMINAL_LONGITUDE Decimal(9,6) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(4) NOT NULL,
    LIN_TIPO_ID VARCHAR(4) NOT NULL,
    PRIMARY KEY (LIN_TERMINAL_NOME, GLB_MUNICIPIO_COD),
    FOREIGN KEY (GLB_UF_SIGLA) REFERENCES T_GLB_UF(GLB_UF_SIGLA),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);
