-- ========================================
-- VEHICLE MODULE TABLES
-- ========================================

CREATE TABLE T_VEI_GARAGEM (
   VEI_GARAGEM_ID BIGSERIAL PRIMARY KEY,
   VEI_GARAGEM_DESCRICAO VARCHAR(155) NOT NULL,
   GLB_MUNICIPIO_COD BIGINT NOT NULL,
   GLB_OPERADOR_CNPJ VARCHAR(14) NOT NULL,
   VEI_GARAGEM_LOGRADOURO VARCHAR(255) NOT NULL,
   VEI_GARAGEM_NUMERO VARCHAR(24) NOT NULL,
   VEI_GARAGEM_CEP VARCHAR(8) NOT NULL,
   CONSTRAINT FK_GARAGEM_OPERADOR FOREIGN KEY (GLB_OPERADOR_CNPJ)
           REFERENCES T_GLB_OPERADOR (GLB_OPERADOR_CNPJ),
   CONSTRAINT FK_GARAGEM_MUNICIPIO FOREIGN KEY (GLB_MUNICIPIO_COD)
           REFERENCES ibge.T_GLB_MUNICIPIO (GLB_MUNICIPIO_COD)
);

CREATE TABLE T_VEI_VEICULOMODELO (
    VEI_VEICULOMODELO_ID BIGSERIAL PRIMARY KEY,
    VEI_VEICULO_MARCA VARCHAR(256) NOT NULL,
    VEI_VEICULO_MODELO VARCHAR(256) NOT NULL,
    VEI_VEICULO_EIXO INT NOT NULL,
    VEI_VEICULO_TIPO VARCHAR(128) NOT NULL
);

CREATE TABLE T_VEI_VEICULO (
    VEI_VEICULO_PLACA VARCHAR(16) PRIMARY KEY,
    VEI_VEICULO_ID VARCHAR(100) NOT NULL,
    GLB_OPERADOR_CNPJ VARCHAR(14) NOT NULL,
    VEI_VEICULOMODELO_ID BIGINT NOT NULL,
    VEI_VEICULO_CAPACIDADE INT NOT NULL,
    VEI_VEICULO_ANOFABRICACAO VARCHAR(4) NOT NULL,
    VEI_GARAGEM_ID BIGSERIAL NOT NULL,
    VEI_VEICULO_FLAGATIVO VARCHAR(1) DEFAULT 'S' NOT NULL CHECK (VEI_VEICULO_FLAGATIVO IN ('S', 'N')),
    VEI_VEICULO_DTCADASTRO DATE DEFAULT CURRENT_DATE,
    CONSTRAINT FK_VEI_MODELO_ID FOREIGN KEY (VEI_VEICULOMODELO_ID)
        REFERENCES T_VEI_VEICULOMODELO (VEI_VEICULOMODELO_ID),
    CONSTRAINT FK_VEI_OPERADOR_CNPJ FOREIGN KEY (GLB_OPERADOR_CNPJ)
        REFERENCES T_GLB_OPERADOR (GLB_OPERADOR_CNPJ),
    CONSTRAINT FK_GARAGEM_ID FOREIGN KEY (VEI_GARAGEM_ID)
        REFERENCES T_VEI_GARAGEM (VEI_GARAGEM_ID)
);

-- ========================================
-- LINK TABLES (Vehicle ↔ Line / Driver)
-- ========================================

CREATE TABLE T_VEI_LINHAPLACA (
    LIN_LINHA_ID VARCHAR(30) NOT NULL,
    LIN_LINHA_ATENDIMENTO VARCHAR(15) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    VEI_VEICULO_PLACA VARCHAR(16) NOT NULL,
    VEI_LINHAPLACA_DIASEMANA VARCHAR(30) NOT NULL CHECK (
        VEI_LINHAPLACA_DIASEMANA IN (
            'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO'
        )
    ),
    VEI_LINHAPLACA_HORAINICIO TIME,
    VEI_LINHAPLACA_HORAFIM TIME,
    VEI_LINHAPLACA_DTGRAV DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD, VEI_VEICULO_PLACA, VEI_LINHAPLACA_DIASEMANA),
    CONSTRAINT FK_LINHAPLACA_LINHA FOREIGN KEY (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD)
        REFERENCES T_LIN_LINHA (LIN_LINHA_ID, LIN_LINHA_ATENDIMENTO, GLB_MUNICIPIO_COD),
    CONSTRAINT FK_LINHAPLACA_VEICULO FOREIGN KEY (VEI_VEICULO_PLACA)
        REFERENCES T_VEI_VEICULO (VEI_VEICULO_PLACA)
);

CREATE TABLE T_VEI_MOTORISTAPLACA (
    USU_USUARIO_CPF VARCHAR(11) NOT NULL,
    VEI_VEICULO_PLACA VARCHAR(16) NOT NULL,
    VEI_MOTORISTAPLACA_DIASEMANA VARCHAR(30) NOT NULL CHECK (
        VEI_MOTORISTAPLACA_DIASEMANA IN (
            'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO'
        )
    ),
    VEI_MOTORISTAPLACA_HORAINICIO TIME NOT NULL,
    VEI_MOTORISTAPLACA_HORAFIM TIME NOT NULL,
    VEI_MOTORISTAPLACA_DTGRAV DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (USU_USUARIO_CPF, VEI_MOTORISTAPLACA_DIASEMANA),
    CONSTRAINT FK_MOTORISTAPLACA_USUARIO FOREIGN KEY (USU_USUARIO_CPF)
        REFERENCES T_USU_USUARIO (USU_USUARIO_CPF),
    CONSTRAINT FK_MOTORISTAPLACA_VEICULO FOREIGN KEY (VEI_VEICULO_PLACA)
        REFERENCES T_VEI_VEICULO (VEI_VEICULO_PLACA)
);

-- ========================================
-- DRIVER TIMETABLE TABLE
-- ========================================

CREATE TABLE T_USU_MOTORISTAHORA (
    USU_USUARIO_CPF VARCHAR(11) NOT NULL,
    USU_MOTORISTAHORA_DIASEMANA VARCHAR(30) NOT NULL CHECK (
        USU_MOTORISTAHORA_DIASEMANA IN (
            'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO'
        )
    ),
    USU_MOTORISTAHORA_HORAINICIO TIME NOT NULL,
    USU_MOTORISTAHORA_HORAFIM TIME NOT NULL,
    USU_MOTORISTAHORA_PAUSAINICIO TIME NOT NULL,
    USU_MOTORISTAHORA_PAUSAFIM TIME NOT NULL,
    PRIMARY KEY (USU_USUARIO_CPF, USU_MOTORISTAHORA_DIASEMANA),
    CONSTRAINT FK_MOTORISTAHORA_USUARIO FOREIGN KEY (USU_USUARIO_CPF)
        REFERENCES T_USU_USUARIO (USU_USUARIO_CPF)
);

-- ========================================
-- INDEXES
-- ========================================

CREATE INDEX idx_vei_placa ON T_VEI_VEICULO(VEI_VEICULO_PLACA);
CREATE INDEX idx_vei_operador ON T_VEI_VEICULO(GLB_OPERADOR_CNPJ);
CREATE INDEX idx_linhaplaca_dia ON T_VEI_LINHAPLACA(VEI_LINHAPLACA_DIASEMANA);
CREATE INDEX idx_motoristaplaca_dia ON T_VEI_MOTORISTAPLACA(VEI_MOTORISTAPLACA_DIASEMANA);
CREATE INDEX idx_motoristahora_dia ON T_USU_MOTORISTAHORA(USU_MOTORISTAHORA_DIASEMANA);
CREATE INDEX idx_veiculo_garagem ON T_VEI_VEICULO(VEI_GARAGEM_ID);