-- Create the sequence for LIN_PARADA_ID
CREATE SEQUENCE SEQ_LIN_PARADA_ID
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCACHE
    NOCYCLE;

-- Create the T_LIN_PARADA table
CREATE TABLE T_LIN_PARADA (
    LIN_PARADA_ID BIGINT NOT NULL,
    LIN_PARADA_LOGRADOURO VARCHAR(255) NOT NULL,
    LIN_PARADA_NUMERO VARCHAR(255) NOT NULL,
    LIN_PARADA_LONGITUDE BIGINT NOT NULL,
    LIN_PARADA_LATITUDE BIGINT NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_UF_SIGLA VARCHAR(4) NOT NULL,
    LIN_TIPO_ID VARCHAR(4) NOT NULL,
    PRIMARY KEY (LIN_PARADA_ID, GLB_MUNICIPIO_COD),
    FOREIGN KEY (GLB_UF_SIGLA) REFERENCES T_GLB_UF(GLB_UF_SIGLA),
    FOREIGN KEY (GLB_MUNICIPIO_COD) REFERENCES T_GLB_MUNICIPIO(GLB_MUNICIPIO_COD),
    FOREIGN KEY (LIN_TIPO_ID) REFERENCES T_LIN_TIPO(LIN_TIPO_ID)
);

-- Create a trigger to automatically populate LIN_PARADA_ID using the sequence
CREATE OR REPLACE TRIGGER TRG_LIN_PARADA_ID
BEFORE INSERT ON T_LIN_PARADA
FOR EACH ROW
BEGIN
    :NEW.LIN_PARADA_ID := SEQ_LIN_PARADA_ID.NEXTVAL;
END;
/
