CREATE TABLE T_USU_USUARIO (
    USU_USUARIO_ID              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USU_USUARIO_LOGIN           VARCHAR(50) UNIQUE NOT NULL,
    GLB_OPERADOR_CNPJ            VARCHAR(14) NOT NULL,
    USU_USUARIO_EMAIL           VARCHAR(255) UNIQUE NOT NULL
                                CHECK (USU_USUARIO_EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    USU_USUARIO_SENHA           TEXT NOT NULL,  -- Store only hashed passwords
    USU_USUARIO_NOME            VARCHAR(100),
    USU_USUARIO_TELEFONE        VARCHAR(20) UNIQUE CHECK (USU_USUARIO_TELEFONE ~ '^[0-9]+$'), -- Only digits
    USU_USUARIO_CPF             VARCHAR(11) UNIQUE,
    USU_USUARIO_ROLE            VARCHAR(25) NOT NULL CHECK (USU_USUARIO_ROLE IN ('ADMIN', 'USER', 'MODERATOR', 'MOTORISTA')),
    USU_USUARIO_FLAGATIVO       TEXT NOT NULL DEFAULT 'S' CHECK (USU_USUARIO_FLAGATIVO IN ('S', 'N')),
    USU_USUARIO_DTCRIACAO       TIMESTAMPTZ DEFAULT now(),
    USU_USUARIO_DTUPDATE        TIMESTAMPTZ NULL,
    USU_USUARIO_DTULTIMOLOGIN   TIMESTAMPTZ, -- Keep the same name here
    CONSTRAINT FK_USU_OPERADOR_CNPJ FOREIGN KEY(GLB_OPERADOR_CNPJ)
            REFERENCES T_GLB_OPERADOR(GLB_OPERADOR_CNPJ)
);

-- Create Indexes
CREATE INDEX idx_usuario_login ON T_USU_USUARIO(USU_USUARIO_LOGIN);
CREATE INDEX idx_usuario_email ON T_USU_USUARIO(USU_USUARIO_EMAIL);
CREATE INDEX idx_usuario_role ON T_USU_USUARIO(USU_USUARIO_ROLE);
CREATE INDEX idx_usuario_status ON T_USU_USUARIO(USU_USUARIO_FLAGATIVO);
CREATE INDEX idx_usu_operador_cnpj ON T_USU_USUARIO(GLB_OPERADOR_CNPJ);

-- Trigger Function for Login
CREATE OR REPLACE FUNCTION update_login_info()
RETURNS TRIGGER AS $$
BEGIN
    -- Update last login timestamp
    NEW.USU_USUARIO_DTULTIMOLOGIN = now();  -- Corrected to match the column name
    -- Increment the login count
    NEW.USU_USUARIO_LOGIN_COUNT = NEW.USU_USUARIO_LOGIN_COUNT + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to call the function on login
CREATE TRIGGER trg_update_login_info
AFTER UPDATE OF USU_USUARIO_DTULTIMOLOGIN ON T_USU_USUARIO  -- Corrected to match the column name
FOR EACH ROW
WHEN (OLD.USU_USUARIO_DTULTIMOLOGIN IS NULL OR OLD.USU_USUARIO_DTULTIMOLOGIN < NEW.USU_USUARIO_DTULTIMOLOGIN)
EXECUTE FUNCTION update_login_info();
-- FIM CRIACAO USUARIO

INSERT INTO T_USU_USUARIO (
    USU_USUARIO_LOGIN,
    GLB_OPERADOR_CNPJ,
    USU_USUARIO_EMAIL,
    USU_USUARIO_SENHA,
    USU_USUARIO_NOME,
    USU_USUARIO_TELEFONE,
    USU_USUARIO_CPF,
    USU_USUARIO_ROLE,
    USU_USUARIO_FLAGATIVO,
    USU_USUARIO_DTCRIACAO
) VALUES(
'Mobiadm',
'01234567890123',
'citMobi@citmobi.com.br',
'$2a$10$9BH8374tLxctMcb/ZpBgzuwaOCh.4IEFvExT9H1BcLb0SpuRYSV6q',  -- mobibrasil,
'ADMINISTRADOR DO SISTEMA',
'11999999999',
'72160206008',
'ADMIN',
'S',
NOW()
);

INSERT INTO T_USU_USUARIO (
    USU_USUARIO_LOGIN,
    GLB_OPERADOR_CNPJ,
    USU_USUARIO_EMAIL,
    USU_USUARIO_SENHA,
    USU_USUARIO_NOME,
    USU_USUARIO_TELEFONE,
    USU_USUARIO_CPF,
    USU_USUARIO_ROLE,
    USU_USUARIO_FLAGATIVO,
    USU_USUARIO_DTCRIACAO
) VALUES(
'794582540',
'31974104000120',
'antonioferreira@citmobi.com.br',
'$2a$10$9BH8374tLxctMcb/ZpBgzuwaOCh.4IEFvExT9H1BcLb0SpuRYSV6q',  -- mobibrasil,
'ANTONIO SEBASTIÃO FERREIRA',
'51983606522',
'79458254000',
'MOTORISTA',
'S',
NOW()
);