-- ========================================
-- VEHICLE MODULE TABLES
-- ========================================

CREATE TABLE T_VEI_GARAGEM (
    VEI_GARAGEM_ID BIGSERIAL PRIMARY KEY,
    VEI_GARAGEM_DESCRICAO VARCHAR(155) NOT NULL,
    GLB_MUNICIPIO_COD BIGINT NOT NULL,
    GLB_OPERADOR_ID BIGINT NOT NULL,
    VEI_GARAGEM_LOGRADOURO VARCHAR(255) NOT NULL,
    VEI_GARAGEM_NUMERO VARCHAR(24) NOT NULL,
    VEI_GARAGEM_CEP VARCHAR(8) NOT NULL,
    CONSTRAINT FK_GARAGEM_OPERADOR FOREIGN KEY (GLB_OPERADOR_ID)
        REFERENCES T_GLB_OPERADOR (GLB_OPERADOR_ID),
    CONSTRAINT FK_GARAGEM_MUNICIPIO FOREIGN KEY (GLB_MUNICIPIO_COD)
        REFERENCES ibge.T_GLB_MUNICIPIO (GLB_MUNICIPIO_COD)
);

CREATE TABLE T_VEI_VEICULOMODELO (
    VEI_VEICULOMODELO_ID BIGSERIAL PRIMARY KEY,
    VEI_VEICULO_MARCA VARCHAR(256) NOT NULL,
    VEI_VEICULO_MODELO VARCHAR(256) NOT NULL,
    VEI_VEICULO_EIXO INT NOT NULL,
    VEI_VEICULO_TIPO VARCHAR(128) NOT NULL
);

CREATE TABLE T_VEI_VEICULO (
    VEI_VEICULO_ID BIGSERIAL PRIMARY KEY,
    VEI_VEICULO_PLACA VARCHAR(16) UNIQUE NOT NULL,
    VEI_VEICULO_CODIGO VARCHAR(100) NOT NULL,
    GLB_OPERADOR_ID BIGINT NOT NULL,
    VEI_VEICULOMODELO_ID BIGINT NOT NULL,
    VEI_VEICULO_CAPACIDADE INT NOT NULL,
    VEI_VEICULO_ANOFABRICACAO VARCHAR(4) NOT NULL,
    VEI_GARAGEM_ID BIGINT NOT NULL,
    VEI_VEICULO_STATUS VARCHAR(20) DEFAULT 'ATIVO' NOT NULL CHECK (
        VEI_VEICULO_STATUS IN ('ATIVO', 'MANUTENCAO', 'INATIVO', 'SUCATEADO', 'VENDIDO')
    ),
    VEI_VEICULO_DTCADASTRO DATE DEFAULT CURRENT_DATE,
    CONSTRAINT FK_VEI_MODELO_ID FOREIGN KEY (VEI_VEICULOMODELO_ID)
        REFERENCES T_VEI_VEICULOMODELO (VEI_VEICULOMODELO_ID),
    CONSTRAINT FK_VEI_OPERADOR_ID FOREIGN KEY (GLB_OPERADOR_ID)
        REFERENCES T_GLB_OPERADOR (GLB_OPERADOR_ID),
    CONSTRAINT FK_GARAGEM_ID FOREIGN KEY (VEI_GARAGEM_ID)
        REFERENCES T_VEI_GARAGEM (VEI_GARAGEM_ID)
);

-- ========================================
-- SCHEDULE TABLES (Vehicle ↔ Line / Driver)
-- ========================================

CREATE TABLE T_VEI_LINHAPLACA (
    VEI_LINHAPLACA_ID BIGSERIAL PRIMARY KEY,
    LIN_LINHA_ID BIGINT NOT NULL,
    VEI_VEICULO_ID BIGINT NOT NULL,
    VEI_LINHAPLACA_DIASEMANA VARCHAR(30) NOT NULL CHECK (
        VEI_LINHAPLACA_DIASEMANA IN (
            'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO'
        )
    ),
    VEI_LINHAPLACA_HORAINICIO TIME,
    VEI_LINHAPLACA_HORAFIM TIME,
    VEI_LINHAPLACA_DTGRAV DATE DEFAULT CURRENT_DATE,
    CONSTRAINT UK_LINHAPLACA_ESCALA UNIQUE (LIN_LINHA_ID, VEI_VEICULO_ID, VEI_LINHAPLACA_DIASEMANA),
    CONSTRAINT FK_LINHAPLACA_LINHA FOREIGN KEY (LIN_LINHA_ID)
        REFERENCES T_LIN_LINHA (LIN_LINHA_ID),
    CONSTRAINT FK_LINHAPLACA_VEICULO FOREIGN KEY (VEI_VEICULO_ID)
        REFERENCES T_VEI_VEICULO (VEI_VEICULO_ID)
);

CREATE TABLE T_VEI_MOTORISTAPLACA (
    VEI_MOTORISTAPLACA_ID BIGSERIAL PRIMARY KEY,
    USU_USUARIO_ID UUID NOT NULL,
    VEI_VEICULO_ID BIGINT NOT NULL,
    VEI_MOTORISTAPLACA_DIASEMANA VARCHAR(30) NOT NULL CHECK (
        VEI_MOTORISTAPLACA_DIASEMANA IN (
            'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO'
        )
    ),
    VEI_MOTORISTAPLACA_HORAINICIO TIME NOT NULL,
    VEI_MOTORISTAPLACA_HORAFIM TIME NOT NULL,
    VEI_MOTORISTAPLACA_DTGRAV DATE DEFAULT CURRENT_DATE,
    CONSTRAINT UK_MOTORISTAPLACA_ESCALA UNIQUE (USU_USUARIO_ID, VEI_MOTORISTAPLACA_DIASEMANA),
    CONSTRAINT FK_MOTORISTAPLACA_USUARIO FOREIGN KEY (USU_USUARIO_ID)
        REFERENCES T_USU_USUARIO (USU_USUARIO_ID),
    CONSTRAINT FK_MOTORISTAPLACA_VEICULO FOREIGN KEY (VEI_VEICULO_ID)
        REFERENCES T_VEI_VEICULO (VEI_VEICULO_ID)
);

CREATE TABLE T_USU_MOTORISTAHORA (
    USU_MOTORISTAHORA_ID BIGSERIAL PRIMARY KEY,
    USU_USUARIO_ID UUID NOT NULL,
    USU_MOTORISTAHORA_DIASEMANA VARCHAR(30) NOT NULL CHECK (
        USU_MOTORISTAHORA_DIASEMANA IN (
            'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO'
        )
    ),
    USU_MOTORISTAHORA_HORAINICIO TIME NOT NULL,
    USU_MOTORISTAHORA_HORAFIM TIME NOT NULL,
    USU_MOTORISTAHORA_PAUSAINICIO TIME NOT NULL,
    USU_MOTORISTAHORA_PAUSAFIM TIME NOT NULL,
    CONSTRAINT UK_MOTORISTAHORA_ESCALA UNIQUE (USU_USUARIO_ID, USU_MOTORISTAHORA_DIASEMANA),
    CONSTRAINT FK_MOTORISTAHORA_USUARIO FOREIGN KEY (USU_USUARIO_ID)
        REFERENCES T_USU_USUARIO (USU_USUARIO_ID)
);

-- ========================================
-- OPERATIONAL TRIP SESSIONS & TELEMETRY
-- ========================================

CREATE TABLE T_USU_VIAGEM (
    USU_VIAGEM_ID BIGSERIAL PRIMARY KEY,
    USU_USUARIO_ID UUID NOT NULL,
    VEI_VEICULO_ID BIGINT NOT NULL,
    LIN_LINHA_ID BIGINT NOT NULL,
    LIN_ROTA_ID BIGINT NOT NULL,
    USU_VIAGEM_DTINICIO TIMESTAMPTZ NOT NULL DEFAULT now(),
    USU_VIAGEM_DTFIM TIMESTAMPTZ NULL,
    USU_VIAGEM_STATUS VARCHAR(20) DEFAULT 'EM_ANDAMENTO' NOT NULL CHECK (
        USU_VIAGEM_STATUS IN ('EM_ANDAMENTO', 'FINALIZADA', 'CANCELADA')
    ),
    CONSTRAINT FK_VIAGEM_USUARIO FOREIGN KEY (USU_USUARIO_ID)
        REFERENCES T_USU_USUARIO (USU_USUARIO_ID),
    CONSTRAINT FK_VIAGEM_VEICULO FOREIGN KEY (VEI_VEICULO_ID)
        REFERENCES T_VEI_VEICULO (VEI_VEICULO_ID),
    CONSTRAINT FK_VIAGEM_LINHA FOREIGN KEY (LIN_LINHA_ID)
        REFERENCES T_LIN_LINHA (LIN_LINHA_ID),
    CONSTRAINT FK_VIAGEM_ROTA FOREIGN KEY (LIN_ROTA_ID)
        REFERENCES T_LIN_ROTA (LIN_ROTA_ID)
);

CREATE TABLE T_VEI_TELEMETRIA (
    VEI_VEICULO_ID BIGINT PRIMARY KEY,
    USU_VIAGEM_ID BIGINT NOT NULL,
    VEI_TELEMETRIA_LATITUDE DECIMAL(8,6) NOT NULL,
    VEI_TELEMETRIA_LONGITUDE DECIMAL(9,6) NOT NULL,
    VEI_TELEMETRIA_VELOCIDADE DECIMAL(6,2) DEFAULT 0.00,
    VEI_TELEMETRIA_BEARING DECIMAL(5,2) DEFAULT 0.00,
    VEI_TELEMETRIA_ODOMETER DECIMAL(10,2) DEFAULT 0.00,
    VEI_TELEMETRIA_SEQPARADA INT NULL,
    VEI_TELEMETRIA_STATUSPARADA VARCHAR(30) NULL,
    LIN_PARADA_ID BIGINT NULL,
    VEI_TELEMETRIA_DTUPDATE TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT FK_TELEMETRIA_VEICULO FOREIGN KEY (VEI_VEICULO_ID)
        REFERENCES T_VEI_VEICULO (VEI_VEICULO_ID),
    CONSTRAINT FK_TELEMETRIA_VIAGEM FOREIGN KEY (USU_VIAGEM_ID)
        REFERENCES T_USU_VIAGEM (USU_VIAGEM_ID),
    CONSTRAINT FK_TELEMETRIA_PARADA FOREIGN KEY (LIN_PARADA_ID)
        REFERENCES T_LIN_PARADA (LIN_PARADA_ID)
);

CREATE TABLE T_VEI_TELEMETRIA_HISTORICO (
    VEI_TELEMETRIAHIST_ID BIGSERIAL PRIMARY KEY,
    USU_VIAGEM_ID BIGINT NOT NULL,
    VEI_TELEMETRIA_LATITUDE DECIMAL(8,6) NOT NULL,
    VEI_TELEMETRIA_LONGITUDE DECIMAL(9,6) NOT NULL,
    VEI_TELEMETRIA_VELOCIDADE DECIMAL(6,2) DEFAULT 0.00,
    VEI_TELEMETRIA_BEARING DECIMAL(5,2) DEFAULT 0.00,
    VEI_TELEMETRIA_ODOMETER DECIMAL(10,2) DEFAULT 0.00,
    VEI_TELEMETRIA_DTREGISTRO TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT FK_TELEMHIST_VIAGEM FOREIGN KEY (USU_VIAGEM_ID)
        REFERENCES T_USU_VIAGEM (USU_VIAGEM_ID)
);

-- ========================================
-- INDEXES
-- ========================================

CREATE INDEX idx_vei_placa ON T_VEI_VEICULO(VEI_VEICULO_PLACA);
CREATE INDEX idx_vei_operador ON T_VEI_VEICULO(GLB_OPERADOR_ID);
CREATE INDEX idx_vei_status ON T_VEI_VEICULO(VEI_VEICULO_STATUS);
CREATE INDEX idx_linhaplaca_dia ON T_VEI_LINHAPLACA(VEI_LINHAPLACA_DIASEMANA);
CREATE INDEX idx_motoristaplaca_dia ON T_VEI_MOTORISTAPLACA(VEI_MOTORISTAPLACA_DIASEMANA);
CREATE INDEX idx_motoristahora_dia ON T_USU_MOTORISTAHORA(USU_MOTORISTAHORA_DIASEMANA);
CREATE INDEX idx_veiculo_garagem ON T_VEI_VEICULO(VEI_GARAGEM_ID);
CREATE INDEX idx_viagem_status ON T_USU_VIAGEM(USU_VIAGEM_STATUS);
CREATE INDEX idx_viagem_driver ON T_USU_VIAGEM(USU_USUARIO_ID);
CREATE INDEX idx_telemhist_viagem_time ON T_VEI_TELEMETRIA_HISTORICO(USU_VIAGEM_ID, VEI_TELEMETRIA_DTREGISTRO DESC);