CREATE TABLE IF NOT EXISTS ibge.T_GLB_REGIAO (
    GLB_REGIAO_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_REGIAO_NOME VARCHAR(100),
    GLB_REGIAO_SIGLA VARCHAR(4)
);

CREATE TABLE IF NOT EXISTS ibge.T_GLB_REGIAOINTERMEDIARIA (
    GLB_REGIAOINTERMEDIARIA_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_REGIAOINTERMEDIARIA_NOME VARCHAR(150),
    GLB_UF_COD BIGINT,
    CONSTRAINT FK_GLB_REGIAOINTERMEDIARIA_UF FOREIGN KEY (GLB_UF_COD)
        REFERENCES ibge.T_GLB_UF (GLB_UF_COD)
);

CREATE TABLE IF NOT EXISTS ibge.T_GLB_REGIAOIMEDIATA (
    GLB_REGIAOIMEDIATA_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_REGIAOIMEDIATA_NOME VARCHAR(150),
    GLB_REGIAOINTERMEDIARIA_COD BIGINT,
    CONSTRAINT FK_GLB_REGIAOIMEDIATA_INTERMEDIARIA FOREIGN KEY (GLB_REGIAOINTERMEDIARIA_COD)
        REFERENCES ibge.T_GLB_REGIAOINTERMEDIARIA (GLB_REGIAOINTERMEDIARIA_COD)
);

CREATE TABLE IF NOT EXISTS ibge.T_GLB_DISTRITO (
    GLB_DISTRITO_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_DISTRITO_NOME VARCHAR(150),
    GLB_MUNICIPIO_COD BIGINT,
    CONSTRAINT FK_GLB_DISTRITO_MUNICIPIO FOREIGN KEY (GLB_MUNICIPIO_COD)
        REFERENCES ibge.T_GLB_MUNICIPIO (GLB_MUNICIPIO_COD)
);

CREATE TABLE IF NOT EXISTS ibge.T_GLB_SUBDISTRITO (
    GLB_SUBDISTRITO_COD BIGINT NOT NULL PRIMARY KEY,
    GLB_SUBDISTRITO_NOME VARCHAR(150),
    GLB_DISTRITO_COD BIGINT,
    CONSTRAINT FK_GLB_SUBDISTRITO_DISTRITO FOREIGN KEY (GLB_DISTRITO_COD)
        REFERENCES ibge.T_GLB_DISTRITO (GLB_DISTRITO_COD)
);

ALTER TABLE ibge.T_GLB_UF
    ADD COLUMN IF NOT EXISTS GLB_REGIAO_COD BIGINT,
    ADD CONSTRAINT FK_GLB_UF_REGIAO FOREIGN KEY (GLB_REGIAO_COD)
        REFERENCES ibge.T_GLB_REGIAO (GLB_REGIAO_COD);

ALTER TABLE ibge.T_GLB_MUNICIPIO
    ADD COLUMN IF NOT EXISTS GLB_REGIAOIMEDIATA_COD BIGINT,
    ADD CONSTRAINT FK_GLB_MUNICIPIO_REGIAOIMEDIATA FOREIGN KEY (GLB_REGIAOIMEDIATA_COD)
        REFERENCES ibge.T_GLB_REGIAOIMEDIATA (GLB_REGIAOIMEDIATA_COD);
